### ISSUE TITLE
Widgets in wysiwyg editor

### ISSUE THREAD

**Issue by BobWez98** [rapidez/core#53]
Currently for example someone can set a widget in a wysiwyg editor. But this isn't compatible with the `@widget` directive. The wysiwyg editor gives this as widget:
```
{{widget type="Magento\Widget\Etc" var1="value" var2="value" template="widget/content/template.phtml"}}
```

**Comment by royduin** [comment]
You can now use the `@content` directive to parse these variables, see the docs: https://docs.rapidez.io/0.x/theming.html#content
